; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu May 06 2021 10:03:46 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


