; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1 on Wed May 05 2021 09:21:56 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
; Probe the bed at 7 points
G30 P0 X0 Y84.9 H0 Z-99999
G30 P1 X73.53 Y-42.45 H0 Z-99999
G30 P2 X-73.53 Y-42.45 H0 Z-99999
G30 P3 X0 Y42.4 H0 Z-99999
G30 P4 X36.72 Y-21.2 H0 Z-99999
G30 P5 X-36.72 Y-21.2 H0 Z-99999
G30 P6 X0 Y0 H0 Z-99999 S


