; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Thu May 06 2021 15:00:30 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
M116 P0

